// Sani Building Corp — deterministic estimator guardrails v1.2
const RULES={paintingSfPerHour:30,engineeredHardwoodSfPerHour:14,largeFormatTileSfPerHour:4,markupDefault:25};
const num=v=>{const n=Number(v);return Number.isFinite(n)&&n>0?n:0};
const money=v=>Math.round((Number(v)||0)*100)/100;
const text=v=>String(v==null?'':v).trim();
const norm=v=>text(v).toLowerCase();
const sumLines=lines=>(lines||[]).reduce((s,l)=>s+num(l.qty)*num(l.rate),0);
function evidence(input,analysis){return[input?.request?.description,input?.request?.sqft,JSON.stringify(input?.request?.groupedAnswers||{}),JSON.stringify(analysis?.quantities||{}),JSON.stringify(analysis?.confirmed_scope||[])].filter(Boolean).join(' | ')}
function findQty(e,patterns){for(const re of patterns){const m=e.match(re);if(m)return num(String(m[1]).replace(/,/g,''))}return 0}
function extractQuantities(input,analysis){const e=evidence(input,analysis);return{paintingSf:findQty(e,[/(?:paint(?:ing|able)?|walls?\s*(?:and|\+|,)\s*ceilings?)[^\d]{0,80}([\d,]+(?:\.\d+)?)\s*(?:sf|sq\.?\s*ft|square\s*feet)/i,/([\d,]+(?:\.\d+)?)\s*(?:sf|sq\.?\s*ft|square\s*feet)[^|]{0,80}(?:paint(?:ing|able)?|walls?\s*(?:and|\+|,)\s*ceilings?)/i]),flooringSf:findQty(e,[/(?:engineered\s+hardwood|hardwood\s+floor(?:ing)?|flooring)[^\d]{0,80}([\d,]+(?:\.\d+)?)\s*(?:sf|sq\.?\s*ft|square\s*feet)/i,/([\d,]+(?:\.\d+)?)\s*(?:sf|sq\.?\s*ft|square\s*feet)[^|]{0,80}(?:engineered\s+hardwood|hardwood\s+floor(?:ing)?|flooring)/i]),tileSf:findQty(e,[/(?:24\s*[x×]\s*48|large[- ]format\s+tile|wall\s*(?:and|&)\s*floor\s*tile)[^\d]{0,80}([\d,]+(?:\.\d+)?)\s*(?:sf|sq\.?\s*ft|square\s*feet)/i,/([\d,]+(?:\.\d+)?)\s*(?:sf|sq\.?\s*ft|square\s*feet)[^|]{0,80}(?:24\s*[x×]\s*48|large[- ]format\s+tile)/i])}}
function laborMatches(line,kind){const s=norm(`${line.section||''} ${line.item||''}`);if(kind==='painting')return/paint|painter|wall.*ceiling|ceiling.*wall/.test(s);if(kind==='flooring')return/engineered hardwood|hardwood floor|flooring install|floor installer/.test(s)&&!/bath|tile|shower/.test(s);if(kind==='tile')return/tile setter|tile install|large[- ]format|24\s*[x×]\s*48/.test(s);return false}
function enforce(estimate,kind,min,reason,adj){if(!min)return;const ms=(estimate.labor||[]).filter(l=>laborMatches(l,kind));if(!ms.length){adj.push({type:'MISSING_PRODUCTION_LINE',kind,minimumHours:Math.ceil(min),reason});return}const current=ms.reduce((s,l)=>s+num(l.qty),0);if(current+0.01>=min)return;const target=ms.slice().sort((a,b)=>num(b.qty)-num(a.qty))[0];target.qty=Math.ceil(num(target.qty)+(min-current));adj.push({type:'PRODUCTION_HOURS_RAISED',kind,fromHours:current,toHours:ms.reduce((s,l)=>s+num(l.qty),0),changedLine:target.item,reason})}
function altCode(line){const s=norm(`${line.item||''} ${line.description||''} ${line.label||''}`),m=s.match(/\boption\s*([b-z])\b/);if(m)return`option ${m[1].toUpperCase()}`;if(/\balternate\b|\balternative\b/.test(s))return'Alternate';return''}
function isAlt(line){return!!altCode(line)}
function isolateAlternatives(estimate,adj){estimate.options=Array.isArray(estimate.options)?estimate.options:[];const grouped={};['labor','materials'].forEach(bucket=>{const keep=[];(estimate[bucket]||[]).forEach(line=>{const code=altCode(line);if(!code)return keep.push(line);const key=`${text(line.section)||'General'}|${code}`,base=num(line.qty)*num(line.rate);grouped[key]=grouped[key]||{section:line.section||'General',label:`${code} — alternative`,description:'Mutually exclusive alternative; excluded from base Grand Total',raw:0};grouped[key].raw+=base;adj.push({type:'ALTERNATIVE_REMOVED_FROM_BASE',bucket,item:line.item,baseCost:money(base)})});estimate[bucket]=keep});const mm=1+num(estimate.markupPct||RULES.markupDefault)/100;Object.values(grouped).forEach(o=>{if(!(estimate.options||[]).some(x=>norm(x.label)===norm(o.label)&&canonicalService(x.section,x.label,[])===canonicalService(o.section,o.label,[])))estimate.options.push({section:o.section,label:o.label,description:o.description,price:money(o.raw*mm)})})}
function canonicalService(section,item,selected){const s=norm(`${section||''} ${item||''}`),sel=(selected||[]).map(norm),has=n=>sel.some(x=>x.includes(n));if(/window/.test(s))return'Windows';if(/paint|painter|primer|spackle/.test(s)&&has('paint'))return'Painting';if(/engineered hardwood|hardwood floor|flooring|quarter.?round|subfloor|transition|baseboard/.test(s)&&!/bath|tile|shower/.test(s))return'Flooring';if(/bath|shower|vanity|toilet|plumb|waterproof|backer|thinset|grout|tile|glass|glaz|faucet/.test(s))return'Bathroom';if(/project management|supervision|coordination|general conditions|general labor|cleanup|site protection/.test(s))return'General';return text(section)||'General'}
function normalizeOwnership(estimate,analysis,adj){const selected=analysis?.selected_trades||[];['labor','materials'].forEach(bucket=>(estimate[bucket]||[]).forEach(line=>{const next=canonicalService(line.section,line.item,selected);if(next&&next!==line.section){adj.push({type:'SERVICE_REASSIGNED',bucket,item:line.item,from:line.section,to:next});line.section=next}}));(estimate.customerSupplied||[]).forEach(x=>{if(x&&typeof x==='object')x.section=canonicalService(x.section,x.item,selected)});(estimate.options||[]).forEach(o=>o.section=canonicalService(o.section,`${o.label||''} ${o.description||''}`,selected))}
function calculateTotals(estimate){const labor=money(sumLines(estimate.labor)),materials=money(sumLines(estimate.materials)),subtotal=money(labor+materials),markupPct=Number.isFinite(Number(estimate.markupPct))?Number(estimate.markupPct):RULES.markupDefault,markup=money(subtotal*markupPct/100);return{labor,materials,subtotal,markupPct,markup,grandTotal:money(subtotal+markup)}}
function buildHealth(estimate,analysis,q,adj){const issues=[];if((estimate.labor||[]).some(isAlt)||(estimate.materials||[]).some(isAlt))issues.push({severity:'BLOCK',code:'ALTERNATIVE_IN_BASE_TOTAL',message:'A mutually exclusive alternate is still inside base labor/materials.'});if(q.paintingSf&&!(estimate.labor||[]).some(l=>laborMatches(l,'painting')))issues.push({severity:'REVIEW',code:'PAINTING_RATE_NOT_APPLIED',message:'Painting quantity found but no production line recognized.'});if(q.flooringSf&&!(estimate.labor||[]).some(l=>laborMatches(l,'flooring')))issues.push({severity:'REVIEW',code:'FLOORING_RATE_NOT_APPLIED',message:'Flooring quantity found but no production line recognized.'});if(q.tileSf&&!(estimate.labor||[]).some(l=>laborMatches(l,'tile')))issues.push({severity:'REVIEW',code:'TILE_RATE_NOT_APPLIED',message:'Tile quantity found but no production line recognized.'});return{status:issues.some(i=>i.severity==='BLOCK')?'BLOCKED':issues.length?'REVIEW':'PASS',issues,quantities:q,totals:calculateTotals(estimate),deterministicAdjustments:adj,checkedAt:new Date().toISOString(),version:'deterministic-v1.2'}}
function applyDeterministicPricing(estimate,analysis,input){const out=JSON.parse(JSON.stringify(estimate||{}));out.labor=Array.isArray(out.labor)?out.labor:[];out.materials=Array.isArray(out.materials)?out.materials:[];const adj=[],q=extractQuantities(input||{},analysis||{});isolateAlternatives(out,adj);normalizeOwnership(out,analysis||{},adj);enforce(out,'painting',q.paintingSf?q.paintingSf/RULES.paintingSfPerHour:0,`${q.paintingSf} paintable SF ÷ ${RULES.paintingSfPerHour} SF/labor-hour`,adj);enforce(out,'flooring',q.flooringSf?q.flooringSf/RULES.engineeredHardwoodSfPerHour:0,`${q.flooringSf} flooring SF ÷ ${RULES.engineeredHardwoodSfPerHour} SF/labor-hour`,adj);enforce(out,'tile',q.tileSf?q.tileSf/RULES.largeFormatTileSfPerHour:0,`${q.tileSf} large-format tile SF ÷ ${RULES.largeFormatTileSfPerHour} SF/labor-hour`,adj);out.deterministicPricing={version:'v1.2',quantities:q,adjustments:adj};out.estimateHealth=buildHealth(out,analysis||{},q,adj);return out}
function phraseKey(s){return norm(s).replace(/&/g,' and ').replace(/\b(sherwin\s*williams|sherwin-williams)\b/g,'paintbrand').replace(/\b(engineered\s+hardwood\s+flooring|engineered\s+hardwood|hardwood\s+flooring)\b/g,'hardwood').replace(/\b(sink\s*\/\s*vanity|vanity\s*\/\s*sink|vanity\s+and\s+sink|sink\s+and\s+vanity)\b/g,'vanity sink').replace(/\b(customer[- ]supplied|customer supplied|customer supply|by customer)\b/g,' ').replace(/\b(provide|provided|use|supply|supplied|install|installation|existing|new|all|the|for|with|work|item|materials?)\b/g,' ').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim()}
function tokenSet(s){return new Set(phraseKey(s).split(' ').filter(x=>x.length>2))}
function near(a,b){const ka=phraseKey(a),kb=phraseKey(b);if(!ka||!kb)return ka===kb;if(ka===kb||ka.includes(kb)||kb.includes(ka))return true;const A=tokenSet(a),B=tokenSet(b);if(!A.size||!B.size)return false;let common=0;A.forEach(x=>{if(B.has(x))common++});return common/Math.min(A.size,B.size)>=.68}
function dedupe(list){const out=[];(list||[]).map(x=>text(typeof x==='string'?x:(x?.item||x?.label||x?.description||''))).filter(Boolean).forEach(x=>{if(!out.some(y=>near(x,y)))out.push(x)});return out}
function selectedCustomerServices(analysis,estimate){const preferred=['Bathroom','Flooring','Painting','Windows'],selected=(analysis?.selected_trades||[]).map(x=>canonicalService(x,x,analysis?.selected_trades||[])),lines=[...(estimate.labor||[]),...(estimate.materials||[])].map(x=>canonicalService(x.section,x.item,analysis?.selected_trades||[])),all=[...selected,...lines];return preferred.filter(x=>all.includes(x))}
function exclusionOwner(x){const s=norm(x);if(/window|scaffold|rigging|exterior/.test(s))return'Windows';if(/paint|kitchen.*paint|tiled shower|skim coat|plaster/.test(s))return'Painting';if(/floor|underlayment|transition|baseboard|subfloor/.test(s))return'Flooring';if(/bath|shower|plumb|fixture|vanity|toilet|glass|tile|waterproof|faucet/.test(s))return'Bathroom';return'Project'}
function consolidateCustomerPresentation(estimate,analysis,input){const out=estimate,services=selectedCustomerServices(analysis,out);if(!services.length)return out;const mm=1+(Number(out.markupPct)||RULES.markupDefault)/100,map={};services.forEach(s=>map[s]={title:s,included:[],customerSupplies:[],notIncluded:[],subtotal:0,options:[]});let generalBase=0;const globalIncluded=[],projectExclusions=[];(out.labor||[]).forEach(l=>{const s=canonicalService(l.section,l.item,analysis?.selected_trades||[]),cost=num(l.qty)*num(l.rate);if(map[s]){map[s].subtotal+=cost;map[s].included.push(l.item)}else{generalBase+=cost;if(text(l.item))globalIncluded.push(text(l.item))}});(out.materials||[]).forEach(m=>{const s=canonicalService(m.section,m.item,analysis?.selected_trades||[]),cost=num(m.qty)*num(m.rate);if(map[s])map[s].subtotal+=cost;else generalBase+=cost});const baseSum=services.reduce((t,s)=>t+map[s].subtotal,0);if(generalBase>0)services.forEach(s=>{const share=baseSum>0?map[s].subtotal/baseSum:1/services.length;map[s].subtotal+=generalBase*share});(out.customerSupplied||[]).forEach(x=>{const item=text(typeof x==='string'?x:x?.item),s=canonicalService(typeof x==='object'?x.section:'',item,analysis?.selected_trades||[]);if(item&&map[s])map[s].customerSupplies.push(item)});(out.exclusions||[]).forEach(x=>{const item=text(x),s=exclusionOwner(item);if(map[s])map[s].notIncluded.push(item);else if(item)projectExclusions.push(item)});(analysis?.confirmed_scope||[]).forEach(block=>{(block?.customer_exclusions||[]).forEach(x=>{const item=text(x),s=canonicalService(block.trade||'',item,analysis?.selected_trades||[]);if(map[s])map[s].notIncluded.push(item);else if(item)projectExclusions.push(item)})});(out.options||[]).forEach(o=>{const s=canonicalService(o.section,`${o.label||''} ${o.description||''}`,analysis?.selected_trades||[]);if(map[s])map[s].options.push(o)});const breakdown=services.map(s=>{const v=map[s];v.included=dedupe(v.included);v.customerSupplies=dedupe(v.customerSupplies);v.notIncluded=dedupe(v.notIncluded).filter(x=>exclusionOwner(x)===s);const opts=[];(v.options||[]).forEach(o=>{const k=phraseKey(`${o.label}|${o.description}`);if(!opts.some(x=>phraseKey(`${x.label}|${x.description}`)===k))opts.push(o)});v.options=opts;v.subtotal=money(v.subtotal*mm);return v});out.serviceBreakdown=breakdown;out.scopeSections=breakdown.map(v=>({title:v.title,items:v.included.slice()}));out.scopeOfWork=out.scopeSections.map(s=>`${s.title.toUpperCase()}:\n${s.items.map(i=>`• ${i}`).join('\n')}`).join('\n\n');out.projectIncluded=dedupe(globalIncluded);out.projectExclusions=dedupe(projectExclusions);out.customerPresentationVersion='v8.2-deterministic-four-service';out.deterministicPresentation={version:'v1.2',services:services.slice(),generalAllocated:money(generalBase*mm),projectIncluded:out.projectIncluded,projectExclusions:out.projectExclusions};return out}
module.exports={RULES,applyDeterministicPricing,extractQuantities,calculateTotals,canonicalService,consolidateCustomerPresentation};
