// Sani Building Corp — deterministic estimator guardrails v1.4
const RULES={paintingSfPerHour:30,engineeredHardwoodSfPerHour:14,largeFormatTileSfPerHour:4,markupDefault:25};
const num=v=>{const n=Number(v);return Number.isFinite(n)&&n>0?n:0};
const money=v=>Math.round((Number(v)||0)*100)/100;
const text=v=>String(v==null?'':v).trim();
const norm=v=>text(v).toLowerCase();
const sumLines=lines=>(lines||[]).reduce((s,l)=>s+num(l.qty)*num(l.rate),0);
function evidence(input,analysis){return[input?.request?.description,input?.request?.sqft,JSON.stringify(input?.request?.groupedAnswers||{}),JSON.stringify(analysis?.quantities||{}),JSON.stringify(analysis?.confirmed_scope||[])].filter(Boolean).join(' | ')}
function requestEvidence(input,analysis){return norm([input?.request?.description,input?.request?.contractorNotes,input?.request?.extraNotes,JSON.stringify(input?.request?.groupedAnswers||{}),JSON.stringify(analysis?.confirmed_scope||[])].filter(Boolean).join(' | '))}
function findQty(e,patterns){for(const re of patterns){const m=e.match(re);if(m)return num(String(m[1]).replace(/,/g,''))}return 0}
function extractQuantities(input,analysis){const e=evidence(input,analysis);return{paintingSf:findQty(e,[/(?:paint(?:ing|able)?|walls?\s*(?:and|\+|,)\s*ceilings?)[^\d]{0,80}([\d,]+(?:\.\d+)?)\s*(?:sf|sq\.?\s*ft|square\s*feet)/i,/([\d,]+(?:\.\d+)?)\s*(?:sf|sq\.?\s*ft|square\s*feet)[^|]{0,80}(?:paint(?:ing|able)?|walls?\s*(?:and|\+|,)\s*ceilings?)/i]),flooringSf:findQty(e,[/(?:engineered\s+hardwood|hardwood\s+floor(?:ing)?|flooring)[^\d]{0,80}([\d,]+(?:\.\d+)?)\s*(?:sf|sq\.?\s*ft|square\s*feet)/i,/([\d,]+(?:\.\d+)?)\s*(?:sf|sq\.?\s*ft|square\s*feet)[^|]{0,80}(?:engineered\s+hardwood|hardwood\s+floor(?:ing)?|flooring)/i]),tileSf:findQty(e,[/(?:24\s*[x×]\s*48|large[- ]format\s+tile|wall\s*(?:and|&)\s*floor\s*tile)[^\d]{0,80}([\d,]+(?:\.\d+)?)\s*(?:sf|sq\.?\s*ft|square\s*feet)/i,/([\d,]+(?:\.\d+)?)\s*(?:sf|sq\.?\s*ft|square\s*feet)[^|]{0,80}(?:24\s*[x×]\s*48|large[- ]format\s+tile)/i])}}
function laborMatches(line,kind){const s=norm(`${line.section||''} ${line.item||''}`);if(kind==='painting')return/paint|painter|wall.*ceiling|ceiling.*wall/.test(s);if(kind==='flooring')return/engineered hardwood|hardwood floor|flooring install|floor installer/.test(s)&&!/bath|tile|shower/.test(s);if(kind==='tile')return/tile setter|tile install|large[- ]format|24\s*[x×]\s*48/.test(s);return false}
function enforce(estimate,kind,min,reason,adj){if(!min)return;const ms=(estimate.labor||[]).filter(l=>laborMatches(l,kind));if(!ms.length){adj.push({type:'MISSING_PRODUCTION_LINE',kind,minimumHours:Math.ceil(min),reason});return}const current=ms.reduce((s,l)=>s+num(l.qty),0);if(current+0.01>=min)return;const target=ms.slice().sort((a,b)=>num(b.qty)-num(a.qty))[0];target.qty=Math.ceil(num(target.qty)+(min-current));adj.push({type:'PRODUCTION_HOURS_RAISED',kind,fromHours:current,toHours:ms.reduce((s,l)=>s+num(l.qty),0),changedLine:target.item,reason})}
function altCode(line){const s=norm(`${line.item||''} ${line.description||''} ${line.label||''}`),m=s.match(/\boption\s*([b-z])\b/);if(m)return`option ${m[1].toUpperCase()}`;if(/\balternate\b|\balternative\b/.test(s))return'Alternate';return''}
function isAlt(line){return!!altCode(line)}
function isolateAlternatives(estimate,adj){estimate.options=Array.isArray(estimate.options)?estimate.options:[];const grouped={};['labor','materials'].forEach(bucket=>{const keep=[];(estimate[bucket]||[]).forEach(line=>{const code=altCode(line);if(!code)return keep.push(line);const key=`${text(line.section)||'General'}|${code}`,base=num(line.qty)*num(line.rate);grouped[key]=grouped[key]||{section:line.section||'General',label:`${code} — alternative`,description:'Mutually exclusive alternative; excluded from base Grand Total',raw:0};grouped[key].raw+=base;adj.push({type:'ALTERNATIVE_REMOVED_FROM_BASE',bucket,item:line.item,baseCost:money(base)})});estimate[bucket]=keep});const mm=1+num(estimate.markupPct||RULES.markupDefault)/100;Object.values(grouped).forEach(o=>{if(!(estimate.options||[]).some(x=>norm(x.label)===norm(o.label)&&canonicalService(x.section,x.label,[])===canonicalService(o.section,o.label,[])))estimate.options.push({section:o.section,label:o.label,description:o.description,price:money(o.raw*mm)})})}
function windowRequested(input,analysis){const e=requestEvidence(input,analysis);return /window/.test(e)&&(/replace|replacement|repair|option\s*a|option\s*b/.test(e))}
function isWindowLine(line){return canonicalService(line?.section,line?.item,[])==='Windows'&&!genericOperation(line?.item)}
function optionLetter(o){const s=norm(`${o?.label||''} ${o?.description||''}`),m=s.match(/\boption\s*([a-z])\b/);return m?m[1].toUpperCase():''}
function ensureWindowOptionEngine(estimate,analysis,input,adj){if(!windowRequested(input,analysis))return;estimate.options=Array.isArray(estimate.options)?estimate.options:[];const mm=1+num(estimate.markupPct||RULES.markupDefault)/100;const hasBase=[...(estimate.labor||[]),...(estimate.materials||[])].some(isWindowLine);const optionA=estimate.options.find(o=>canonicalService(o.section,`${o.label||''} ${o.description||''}`,[])==='Windows'&&optionLetter(o)==='A');if(!hasBase&&optionA&&num(optionA.price)>0){const preMarkup=money(num(optionA.price)/mm);estimate.materials.push({section:'Windows',item:`${text(optionA.label)||'Window Option A'} — selected base allowance`,qty:1,unit:'allowance',rate:preMarkup});estimate.options=estimate.options.filter(o=>o!==optionA);adj.push({type:'BASE_OPTION_PROMOTED',service:'Windows',option:'A',customerPrice:money(optionA.price),baseCost:preMarkup,reason:'Customer requested both window options and Option A was returned only as a priced option; promoted Option A into the base estimate.'})}else if(hasBase&&optionA){estimate.options=estimate.options.filter(o=>o!==optionA);adj.push({type:'DUPLICATE_BASE_OPTION_REMOVED',service:'Windows',option:'A',reason:'Option A already has base labor/material lines.'})}const remainingBase=[...(estimate.labor||[]),...(estimate.materials||[])].some(isWindowLine);estimate.optionSelections=estimate.optionSelections||{};estimate.optionSelections.Windows={selected:'Option A',baseIncluded:remainingBase,alternatives:(estimate.options||[]).filter(o=>canonicalService(o.section,`${o.label||''} ${o.description||''}`,[])==='Windows').map(o=>({label:o.label,description:o.description,price:money(o.price)}))}}
function genericOperation(item){const i=norm(item);if(!i)return false;const specific=/window|paint|primer|spackle|hardwood|flooring|quarter.?round|subfloor|transition|baseboard|bath|shower|vanity|toilet|plumb|waterproof|backer|thinset|grout|tile|glass|glaz|faucet/.test(i);if(specific)return false;return/project management|project coordination|coordination|supervision|general conditions|general labor|final project cleanup|final cleanup|walk[- ]?through|site protection|material haul|walk[- ]?up.*haul|debris removal|debris disposal|disposal haul|jobsite setup/.test(i)}
function canonicalService(section,item,selected){const i=norm(item),sec=norm(section),sel=(selected||[]).map(norm),has=n=>sel.some(x=>x.includes(n));if(genericOperation(i))return'General';if(/window/.test(i))return'Windows';if(/paint|painter|primer|spackle/.test(i)&&has('paint'))return'Painting';if(/engineered hardwood|hardwood floor|flooring|quarter.?round|subfloor|transition|baseboard/.test(i)&&!/bath|tile|shower/.test(i))return'Flooring';if(/bath|shower|vanity|toilet|plumb|waterproof|backer|thinset|grout|tile|glass|glaz|faucet/.test(i))return'Bathroom';if(/window/.test(sec))return'Windows';if(/paint|painter|primer|spackle/.test(sec)&&has('paint'))return'Painting';if(/engineered hardwood|hardwood floor|flooring|quarter.?round|subfloor|transition|baseboard/.test(sec)&&!/bath|tile|shower/.test(sec))return'Flooring';if(/bath|shower|vanity|toilet|plumb|waterproof|backer|thinset|grout|tile|glass|glaz|faucet/.test(sec))return'Bathroom';if(/project management|supervision|coordination|general conditions|general labor|cleanup|site protection/.test(sec))return'General';return text(section)||'General'}
function normalizeOwnership(estimate,analysis,adj){const selected=analysis?.selected_trades||[];['labor','materials'].forEach(bucket=>(estimate[bucket]||[]).forEach(line=>{const next=canonicalService(line.section,line.item,selected);if(next&&next!==line.section){adj.push({type:'SERVICE_REASSIGNED',bucket,item:line.item,from:line.section,to:next});line.section=next}}));(estimate.customerSupplied||[]).forEach(x=>{if(x&&typeof x==='object')x.section=canonicalService(x.section,x.item,selected)});(estimate.options||[]).forEach(o=>o.section=canonicalService(o.section,`${o.label||''} ${o.description||''}`,selected))}
function calculateTotals(estimate){const labor=money(sumLines(estimate.labor)),materials=money(sumLines(estimate.materials)),subtotal=money(labor+materials),markupPct=Number.isFinite(Number(estimate.markupPct))?Number(estimate.markupPct):RULES.markupDefault,markup=money(subtotal*markupPct/100);return{labor,materials,subtotal,markupPct,markup,grandTotal:money(subtotal+markup)}}
function buildHealth(estimate,analysis,q,adj,input){const issues=[];if((estimate.labor||[]).some(isAlt)||(estimate.materials||[]).some(isAlt))issues.push({severity:'BLOCK',code:'ALTERNATIVE_IN_BASE_TOTAL',message:'A mutually exclusive alternate is still inside base labor/materials.'});if(windowRequested(input,analysis)&&![...(estimate.labor||[]),...(estimate.materials||[])].some(isWindowLine))issues.push({severity:'BLOCK',code:'WINDOW_BASE_OPTION_MISSING',message:'Windows were requested, but the selected base Option A has no priced labor/material line. Do not send until Option A is priced.'});if(q.paintingSf&&!(estimate.labor||[]).some(l=>laborMatches(l,'painting')))issues.push({severity:'REVIEW',code:'PAINTING_RATE_NOT_APPLIED',message:'Painting quantity found but no production line recognized.'});if(q.flooringSf&&!(estimate.labor||[]).some(l=>laborMatches(l,'flooring')))issues.push({severity:'REVIEW',code:'FLOORING_RATE_NOT_APPLIED',message:'Flooring quantity found but no production line recognized.'});if(q.tileSf&&!(estimate.labor||[]).some(l=>laborMatches(l,'tile')))issues.push({severity:'REVIEW',code:'TILE_RATE_NOT_APPLIED',message:'Tile quantity found but no production line recognized.'});return{status:issues.some(i=>i.severity==='BLOCK')?'BLOCKED':issues.length?'REVIEW':'PASS',issues,quantities:q,totals:calculateTotals(estimate),deterministicAdjustments:adj,checkedAt:new Date().toISOString(),version:'deterministic-v1.4'}}
function applyDeterministicPricing(estimate,analysis,input){const out=JSON.parse(JSON.stringify(estimate||{}));out.labor=Array.isArray(out.labor)?out.labor:[];out.materials=Array.isArray(out.materials)?out.materials:[];const adj=[],q=extractQuantities(input||{},analysis||{});isolateAlternatives(out,adj);normalizeOwnership(out,analysis||{},adj);ensureWindowOptionEngine(out,analysis||{},input||{},adj);normalizeOwnership(out,analysis||{},adj);enforce(out,'painting',q.paintingSf?q.paintingSf/RULES.paintingSfPerHour:0,`${q.paintingSf} paintable SF ÷ ${RULES.paintingSfPerHour} SF/labor-hour`,adj);enforce(out,'flooring',q.flooringSf?q.flooringSf/RULES.engineeredHardwoodSfPerHour:0,`${q.flooringSf} flooring SF ÷ ${RULES.engineeredHardwoodSfPerHour} SF/labor-hour`,adj);enforce(out,'tile',q.tileSf?q.tileSf/RULES.largeFormatTileSfPerHour:0,`${q.tileSf} large-format tile SF ÷ ${RULES.largeFormatTileSfPerHour} SF/labor-hour`,adj);out.deterministicPricing={version:'v1.4',quantities:q,adjustments:adj};out.estimateHealth=buildHealth(out,analysis||{},q,adj,input||{});return out}
function phraseKey(s){return norm(s).replace(/&/g,' and ').replace(/\b(sherwin\s*williams|sherwin-williams)\b/g,'