// Sani Building Corp — deterministic estimator guardrails v1
// AI interprets scope. This module constrains labor production, alternatives,
// customer-facing service ownership, and estimate-health reconciliation.

const RULES = { paintingSfPerHour: 30, engineeredHardwoodSfPerHour: 14, largeFormatTileSfPerHour: 4, markupDefault: 25 };
const num=v=>{const n=Number(v);return Number.isFinite(n)&&n>0?n:0};
const money=v=>Math.round((Number(v)||0)*100)/100;
const text=v=>String(v==null?'':v).trim();
const norm=v=>text(v).toLowerCase();
const sumLines=lines=>(lines||[]).reduce((s,l)=>s+num(l.qty)*num(l.rate),0);
function evidence(input,analysis){return [input?.request?.description,input?.request?.sqft,JSON.stringify(input?.request?.groupedAnswers||{}),JSON.stringify(analysis?.quantities||{}),JSON.stringify(analysis?.confirmed_scope||[])].filter(Boolean).join(' | ')}
function findQty(e,patterns){for(const re of patterns){const m=e.match(re);if(m)return num(String(m[1]).replace(/,/g,''))}return 0}
function extractQuantities(input,analysis){const e=evidence(input,analysis);return {
 paintingSf:findQty(e,[/(?:paint(?:ing|able)?|walls?\s*(?:and|\+|,)\s*ceilings?)[^\d]{0,80}([\d,]+(?:\.\d+)?)\s*(?:sf|sq\.?\s*ft|square\s*feet)/i,/([\d,]+(?:\.\d+)?)\s*(?:sf|sq\.?\s*ft|square\s*feet)[^|]{0,80}(?:paint(?:ing|able)?|walls?\s*(?:and|\+|,)\s*ceilings?)/i]),
 flooringSf:findQty(e,[/(?:engineered\s+hardwood|hardwood\s+floor(?:ing)?|flooring)[^\d]{0,80}([\d,]+(?:\.\d+)?)\s*(?:sf|sq\.?\s*ft|square\s*feet)/i,/([\d,]+(?:\.\d+)?)\s*(?:sf|sq\.?\s*ft|square\s*feet)[^|]{0,80}(?:engineered\s+hardwood|hardwood\s+floor(?:ing)?|flooring)/i]),
 tileSf:findQty(e,[/(?:24\s*[x×]\s*48|large[- ]format\s+tile|wall\s*(?:and|&)\s*floor\s*tile)[^\d]{0,80}([\d,]+(?:\.\d+)?)\s*(?:sf|sq\.?\s*ft|square\s*feet)/i,/([\d,]+(?:\.\d+)?)\s*(?:sf|sq\.?\s*ft|square\s*feet)[^|]{0,80}(?:24\s*[x×]\s*48|large[- ]format\s+tile)/i])};}
function laborMatches(line,kind){const s=norm(`${line.section||''} ${line.item||''}`);if(kind==='painting')return /paint|painter|wall.*ceiling|ceiling.*wall/.test(s);if(kind==='flooring')return /engineered hardwood|hardwood floor|flooring install|floor installer/.test(s)&&!/bath|tile|shower/.test(s);if(kind==='tile')return /tile setter|tile install|large[- ]format|24\s*[x×]\s*48/.test(s);return false}
function enforce(estimate,kind,min,reason,adj){if(!min)return;const ms=(estimate.labor||[]).filter(l=>laborMatches(l,kind));if(!ms.length){adj.push({type:'MISSING_PRODUCTION_LINE',kind,minimumHours:Math.ceil(min),reason});return}const current=ms.reduce((s,l)=>s+num(l.qty),0);if(current+0.01>=min)return;const target=ms.slice().sort((a,b)=>num(b.qty)-num(a.qty))[0];target.qty=Math.ceil(num(target.qty)+(min-current));adj.push({type:'PRODUCTION_HOURS_RAISED',kind,fromHours:current,toHours:ms.reduce((s,l)=>s+num(l.qty),0),changedLine:target.item,reason})}
function isAlt(line){return /\boption\s*[b-z]\b|\balternate\b|\balternative\b/.test(norm(`${line.item||''} ${line.description||''}`))}
function isolateAlternatives(estimate,adj){estimate.options=Array.isArray(estimate.options)?estimate.options:[];['labor','materials'].forEach(bucket=>{const keep=[];(estimate[bucket]||[]).forEach(line=>{if(!isAlt(line))return keep.push(line);const price=money(num(line.qty)*num(line.rate)*(1+num(estimate.markupPct||RULES.markupDefault)/100));estimate.options.push({section:line.section||'General',label:line.item||'Alternate option',description:`Alternate ${bucket} line; excluded from base Grand Total`,price});adj.push({type:'ALTERNATIVE_REMOVED_FROM_BASE',bucket,item:line.item,price})});estimate[bucket]=keep})}
function canonicalService(section,item,selected){const s=norm(`${section||''} ${item||''}`);const sel=(selected||[]).map(norm);const has=n=>sel.some(x=>x.includes(n));if(/window/.test(s))return 'Windows';if(/paint|painter/.test(s)&&has('paint'))return 'Painting';if(/engineered hardwood|hardwood floor|flooring|quarter.?round|subfloor|transition/.test(s)&&!/bath|tile|shower/.test(s))return 'Flooring';if(/bath|shower|vanity|toilet|plumb|waterproof|backer|thinset|grout|tile|glass|glaz/.test(s))return 'Bathroom';if(/project management|supervision|coordination|general conditions/.test(s))return 'General';return text(section)||'General'}
function normalizeOwnership(estimate,analysis,adj){const selected=analysis?.selected_trades||[];['labor','materials'].forEach(bucket=>(estimate[bucket]||[]).forEach(line=>{const next=canonicalService(line.section,line.item,selected);if(next&&next!==line.section){adj.push({type:'SERVICE_REASSIGNED',bucket,item:line.item,from:line.section,to:next});line.section=next}}));(estimate.options||[]).forEach(o=>o.section=canonicalService(o.section,`${o.label||''} ${o.description||''}`,selected))}
function calculateTotals(estimate){const labor=money(sumLines(estimate.labor)),materials=money(sumLines(estimate.materials)),subtotal=money(labor+materials);const markupPct=Number.isFinite(Number(estimate.markupPct))?Number(estimate.markupPct):RULES.markupDefault;const markup=money(subtotal*markupPct/100);return {labor,materials,subtotal,markupPct,markup,grandTotal:money(subtotal+markup)}}
function buildHealth(estimate,analysis,q,adj){const issues=[];if((estimate.labor||[]).some(isAlt)||(estimate.materials||[]).some(isAlt))issues.push({severity:'BLOCK',code:'ALTERNATIVE_IN_BASE_TOTAL',message:'A mutually exclusive alternate is still inside base labor/materials.'});if(q.paintingSf&&!(estimate.labor||[]).some(l=>laborMatches(l,'painting')))issues.push({severity:'REVIEW',code:'PAINTING_RATE_NOT_APPLIED',message:'Painting quantity found but no production line recognized.'});if(q.flooringSf&&!(estimate.labor||[]).some(l=>laborMatches(l,'flooring')))issues.push({severity:'REVIEW',code:'FLOORING_RATE_NOT_APPLIED',message:'Flooring quantity found but no production line recognized.'});if(q.tileSf&&!(estimate.labor||[]).some(l=>laborMatches(l,'tile')))issues.push({severity:'REVIEW',code:'TILE_RATE_NOT_APPLIED',message:'Tile quantity found but no production line recognized.'});return {status:issues.some(i=>i.severity==='BLOCK')?'BLOCKED':issues.length?'REVIEW':'PASS',issues,quantities:q,totals:calculateTotals(estimate),deterministicAdjustments:adj,checkedAt:new Date().toISOString(),version:'deterministic-v1'}}
function applyDeterministicPricing(estimate,analysis,input){const out=JSON.parse(JSON.stringify(estimate||{}));out.labor=Array.isArray(out.labor)?out.labor:[];out.materials=Array.isArray(out.materials)?out.materials:[];const adj=[],q=extractQuantities(input||{},analysis||{});isolateAlternatives(out,adj);normalizeOwnership(out,analysis||{},adj);enforce(out,'painting',q.paintingSf?q.paintingSf/RULES.paintingSfPerHour:0,`${q.paintingSf} paintable SF ÷ ${RULES.paintingSfPerHour} SF/labor-hour`,adj);enforce(out,'flooring',q.flooringSf?q.flooringSf/RULES.engineeredHardwoodSfPerHour:0,`${q.flooringSf} flooring SF ÷ ${RULES.engineeredHardwoodSfPerHour} SF/labor-hour`,adj);enforce(out,'tile',q.tileSf?q.tileSf/RULES.largeFormatTileSfPerHour:0,`${q.tileSf} large-format tile SF ÷ ${RULES.largeFormatTileSfPerHour} SF/labor-hour`,adj);out.deterministicPricing={version:'v1',quantities:q,adjustments:adj};out.estimateHealth=buildHealth(out,analysis||{},q,adj);return out}
module.exports={RULES,applyDeterministicPricing,extractQuantities,calculateTotals,canonicalService};
