#!/usr/bin/env python3
"""Homepage restyle: cosmetics only, every word and section kept.

  "redesign current home page with fonts, cards and other cosmetics but keep
   original wordings and structure"

Does four things to index.html, and is safe to run again:
  1. adds the Archivo + Source Sans 3 font link to <head>;
  2. re-points every selector that asks for Playfair Display (headings) or
     DM Sans (text) at the new fonts, by reading the page's own CSS - so no
     rule is missed and none is guessed;
  3. appends partials/home-restyle.css LAST, so it wins over the older blocks;
  4. swaps the stock icons for one hand-drawn set (partials/home-icons.svg),
     each icon chosen by the words next to it. The words are not touched.
"""
import re, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
P = ROOT / "index.html"
page = P.read_text()
css = (ROOT / "partials/home-restyle.css").read_text()
sprite = (ROOT / "partials/home-icons.svg").read_text()

HEAD_FONT = "'Archivo',system-ui,-apple-system,'Segoe UI',sans-serif"
TEXT_FONT = "'Source Sans 3',system-ui,-apple-system,'Segoe UI',sans-serif"
FONTS = ('<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>'
         '<link href="https://fonts.googleapis.com/css2?family=Archivo:wdth,wght@75..100,500..800&family=Source+Sans+3:wght@400;500;600;700&display=swap" rel="stylesheet">')

def put(text, start, end, block, where):
    if start in text:
        return re.sub(re.escape(start) + r".*?" + re.escape(end), lambda m: start + block + end, text, flags=re.S)
    i = text.index(where)
    return text[:i] + start + block + end + "\n" + text[i:]

# ── 2. which selectors ask for which font, read from the page's own CSS ──
# (ops/site-readable.js's block is not the page's own CSS either)
own = re.sub(r"<!-- (RESTYLE-CSS|SBC-READABLE):START -->.*?<!-- \1:END -->", "", page, flags=re.S)
styles = "\n".join(re.findall(r"<style[^>]*>(.*?)</style>", own, flags=re.S))
styles = re.sub(r"/\*.*?\*/", "", styles, flags=re.S)
head_sel, text_sel = [], []
for sel, body in re.findall(r"([^{}]+)\{([^{}]*)\}", styles):
    sel = sel.strip()
    if not sel or sel.startswith("@") or "font-family" not in body:
        continue
    for s in (x.strip() for x in sel.split(",")):
        if not s or s.startswith("@") or re.match(r"^(from|to|\d+%)$", s):
            continue
        if "Playfair" in body and s not in head_sel:
            head_sel.append(s)
        elif "DM Sans" in body and s not in text_sel:
            text_sel.append(s)
fonts_css = ""
if text_sel:
    fonts_css += ",".join(text_sel) + "{font-family:" + TEXT_FONT + "!important}\n"
if head_sel:
    fonts_css += ",".join(head_sel) + "{font-family:" + HEAD_FONT + "!important;font-weight:800}\n"
fonts_css += "html body h1,html body h2,html body h3{font-family:" + HEAD_FONT + "!important}\n"

# ── 1 + 3. font link in <head>, the restyle block last in <body> ─────────
page = put(page, "<!-- RESTYLE-FONTS:START -->", "<!-- RESTYLE-FONTS:END -->", FONTS,
           "<!-- SBC-READABLE:START -->" if "<!-- SBC-READABLE:START -->" in page else "</head>")
page = put(page, "<!-- RESTYLE-CSS:START -->", "<!-- RESTYLE-CSS:END -->",
           '<style id="home-restyle">\n/* fonts: generated by ops/home-restyle.py from the page\'s own rules */\n' + fonts_css + css.strip() + "\n</style>", "</body>")

# ── 4. icons ─────────────────────────────────────────────────────────────
page = put(page, "<!-- RESTYLE-ICONS:START -->", "<!-- RESTYLE-ICONS:END -->", sprite.strip(), '<div id="site-menu"></div>')
ICON = lambda name: '<svg class="ri" viewBox="0 0 24 24" aria-hidden="true"><use href="#r-' + name + '"/></svg>'
OLD = r'<svg viewBox="0 0 24 24">(?:(?!</svg>).)*</svg>'

def in_order(text, wrapper_re, names):
    """Replace the old svg inside each wrapper, in page order."""
    it = iter(names)
    def swap(m):
        try:
            return re.sub(OLD, ICON(next(it)), m.group(0), count=1, flags=re.S)
        except StopIteration:
            return m.group(0)
    return re.sub(wrapper_re, swap, text, flags=re.S)

# hero stat cards: Fully Insured, 10+ Years, On-Time & On-Budget, Project Management, 5-Star
page = in_order(page, r'<div class="hstat-icon">\s*' + OLD, ["shield", "building", "clock", "hardhat", "star"])
# the values: Project Management, Project Manager, Premium Materials, Warranty, Showroom, 10+ Years
page = in_order(page, r'<div class="value-icon">\s*' + OLD, ["clipboard", "hardhat", "swatch", "seal", "store", "building"])
# why-us strip: Team, Craftsmanship, Process, On-Time, Built for NYC
page = in_order(page, r'<div class="why-feat-col-icon">' + OLD, ["hardhat", "square", "clipboard", "clock", "city"])
# closing CTA: No commitment, Same-day response, Fully insured
page = in_order(page, r'<div class="cta-info-item">' + OLD, ["check", "clock", "shield"])
# the service marquee: by its label
BY_LABEL = {"Bathrooms": "bath", "Kitchens": "kitchen", "Painting": "paint", "Tile Installation": "tile",
            "Flooring": "floor", "Carpentry": "square", "Decks": "deck", "Water Damage": "water",
            "Handyman": "wrench", "Commercial": "store", "Residential": "house"}
page = re.sub(r'<span class="msvc">(' + OLD + r')<span>([^<]+)</span>',
              lambda m: '<span class="msvc">' + (ICON(BY_LABEL[m.group(2)]) if m.group(2) in BY_LABEL else m.group(1)) + '<span>' + m.group(2) + '</span>',
              page, flags=re.S)

P.write_text(page)
print("index.html restyled: %d heading selectors, %d text selectors" % (len(head_sel), len(text_sel)))
